trigger:
- main

jobs:
  - job:
    displayName: 'Build, Test and Publish'
    pool:
      vmImage: 'ubuntu-latest'
    
    variables:
      - group: 'npm-public-registry-user'

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
      displayName: 'Run npm install and build'

    - script: |
        npm run test
      displayName: 'Run tests'
    
    - script: |
        npm install -g npm-cli-login
      displayName: 'Install NPM login utility'
    
    - script: |
        npm-cli-login -u $(NPM_USERNAME) -p $(NPM_PASSWORD) -e $(NPM_EMAIL)
      displayName: 'Login to public NPM registry'